# Generated by Django 2.2.2 on 2019-09-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_id', models.CharField(max_length=10)),
                ('designer_name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='女性', max_length=4)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10)),
                ('member_name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='女性', max_length=4)),
                ('phone', models.CharField(max_length=12)),
                ('tel_for_home', models.CharField(max_length=12)),
                ('career', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('line_id', models.CharField(max_length=60)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Member_Designer', to='x_cloud.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=20)),
                ('tax_id', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=12)),
                ('fax', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customer_Designer', to='x_cloud.Designer')),
            ],
        ),
    ]
