# Generated by Django 2.2.2 on 2019-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
    ]
